export const SHOP_DATA = [
  {
    title: "flower1",
    imageUrl: "",
    description: "test",
    price: 13,
    id: 1,
  },
  {
    title: "flower2",
    imageUrl: "",
    description: "test",
    price: 16,
    id: 2,
  },
  {
    title: "flower3",
    imageUrl: "",
    description: "test",
    price: 10,
    id: 3,
  },
  {
    title: "flower4",
    imageUrl: "",
    description: "test",
    price: 10,
    id: 4,
  },
  {
    title: "flower5",
    imageUrl: "",
    description: "test",
    price: 26,
    id: 5,
  },
  {
    title: "flower6",
    imageUrl: "",
    description: "test",
    price: 13,
    id: 6,
  },
  {
    title: "flower1",
    imageUrl: "",
    description: "test",
    price: 25,
    id: 7,
  },
  {
    title: "flower2",
    imageUrl: "",
    description: "test",
    price: 22,
    id: 8,
  },
  {
    title: "flower3",
    imageUrl: "",
    description: "test",
    price: 22,
    id: 9,
  },
  {
    title: "flower4",
    imageUrl: "",
    description: "test",
    price: 21,
    id: 10,
  },
  {
    title: "flower5",
    imageUrl: "",
    description: "test",
    price: 18,
    id: 11,
  },
  {
    title: "flower6",
    imageUrl: "",
    description: "test",
    price: 18,
    id: 12,
  },
];
